name: ğŸ§ª Frontend e2e Tests
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”€ Checking out Repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setting up go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.21.6'
      
      - name: â¬‡ï¸ Install dependencies
        run: go mod tidy

      - name: â¬‡ï¸ Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: ğŸ“¦ Installing Dependencies
        run: |
          cd frontend
          npm i -g pnpm
          pnpm install
          sudo apt-get install -y expect
          sudo apt install libgtk-3-dev
          sudo apt install libwebkit2gtk-4.0-dev
      
      - name: ğŸ» Installing Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor

      # - name: ğŸ§ª Run tests
      #   run: |
      #     ls
      #     make e2e-tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: wails dev
          browser: chrome
          wait-on: 'http://localhost:34115'
          wait-on-timeout: 360
        